# Pipeline 1 
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    - script: echo Build
    - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
      inputs:
        connectedServiceName: 'dev146069'
        artifactsPayload: |
          {
             "artifacts": [
                {
                   "name": "_pipeline-1-build.war",
                   "version": "1.$(Build.BuildId)",
                   "semanticVersion": "1.$(Build.BuildId).0",
                   "repositoryName": "pipeline-1-build-deply-cicd"
                }
             ]
          }
- stage: 'Test'
  jobs:
  - job: 'Unit_Tests'
    steps:
    - script: echo Unit Tests
    - task: CmdLine@2
      inputs:
        script: |
          NOW=$(date +"%Y-%m-%dT%T-0500")
          testPayload='{"name":"Test-summary1pipeline-1.$(Build.BuildId).0","duration":0.0,"passedTests":10,"failedTests":1,"skippedTests":0,"blockedTests":0,"totalTests":11,"startTime":"'$NOW'","finishTime":"'$NOW'","artifacts":[{"name":"_pipeline-1-build.war","version":"1.$(Build.BuildId).0"}]}'
          echo $testPayload
          curl -X POST -H 'Content-Type: application/json' -u 'devops.integration.user:Snowdd123!'  -d $testPayload 'https://dev146069.service-now.com/api/sn_devops/v1/devops/tool/test?orchestrationToolId\=03d1d74597c26110e659bb5ef053afed\&toolId=81ec3b8197c66110e659bb5ef053afaf'
  - job: 'Checkmarx_Scan'
    steps:
    - script: echo Checkmarx Scan

- stage: 'Deploy'
  jobs:
  - job: 'UAT_Deploy'
    steps:
    - script: echo UAT Deploy
    - task: ServiceNow-DevOps-Agent-Package-Registration@1
      inputs:
        connectedServiceName: 'dev146069'
        packageName: 'Pipeline1BuildDeploy'
        artifactsPayload: |
          {
              "artifacts": [
              {
                  "name": "_pipeline-1-build.war",
                  "repositoryName": "pipeline-1-build-deply-cicd",
                  "version": "1.$(build.buildId)",
                  "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                  "taskExecutionNumber":"$(build.buildId)",
                  "stageName":"$(system.jobDisplayName)",
                  "branchName":"$(build.sourceBranchName)"
              }],
              "pipelineName":"$(system.teamProject)/$(build.definitionName)",
              "taskExecutionNumber":"$(build.buildId)",
              "stageName":"$(system.jobDisplayName)",
              "branchName":"$(build.sourceBranchName)"
          }

  - job: 'Production_Deploy'
    pool: server
    dependsOn: 'UAT_Deploy'
    steps:
    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'dev146069'
        changeRequestDetails: |
          {
              "setCloseCode" : true,
              "attributes": {
                "requested_by": {
                  "user_name": "devops.integration.user"
                },
                "start_date": "2023-05-05 08:00:00",
                "end_date": "2021-05-08 08:00:00"
              }
            }
