# Pipeline 1 
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    - script: echo Build
    - task: ServiceNow-DevOps-Agent-Artifact-Registration@1
      inputs:
        connectedServiceName: 'dev146069'
        artifactsPayload: |
          {
             "artifacts": [
                {
                   "name": "_pipeline-1-build.war",
                   "version": "1.$(Build.BuildId)",
                   "semanticVersion": "1.$(Build.BuildId).0",
                   "repositoryName": "pipeline-1-build-deply-cicd"
                }
             ]
          }
- stage: 'Test'
  jobs:
  - job: 'Unit_Tests'
    steps:
    - script: echo Unit Tests
  - job: 'Checkmarx_Scan'
    steps:
    - script: echo Checkmarx Scan

- stage: 'Deploy'
  jobs:
  - job: 'UAT_Deploy'
    steps:
    - script: echo UAT Deploy
    - task: ServiceNow-DevOps-Agent-Package-Registration@1
      inputs:
        connectedServiceName: 'dev146069'
        packageName: 'Pipeline1BuildDeploy'
        artifactsPayload: |
          {
              "artifacts": [
              {
                  "name": "_pipeline-1-build.war",
                  "repositoryName": "pipeline-1-build-deply-cicd",
                  "version": "1.$(build.buildId)",
                  "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                  "taskExecutionNumber":"$(build.buildId)",
                  "stageName":"$(system.jobDisplayName)",
                  "branchName":"$(build.sourceBranchName)"
              }],
              "pipelineName":"$(system.teamProject)/$(build.definitionName)",
              "taskExecutionNumber":"$(build.buildId)",
              "stageName":"$(system.jobDisplayName)",
              "branchName":"$(build.sourceBranchName)"
          }

  - job: 'Production_Deploy'
    steps:
    - script: echo Production Deploy
