trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Build'
  jobs:
  - job: 'Build'
    steps:
    - script: echo Build
    
- stage: 'Test'
  jobs:
  - job: 'Unit_Tests'
    steps:
    - script: echo Unit Tests
  - job: 'Checkmarx_Scan'
    steps:
    - script: echo Checkmarx Scan

- stage: 'Deploy'
  jobs:
  - job: 'Production_Deploy'
    steps:
    - script: echo Checkmarx Scan